### ISSUE TITLE
Missing XJSSpreadAttribute

### ISSUE THREAD

**Issue by nzakas** [RReverser/estraverse-fb#2]
The `XJSSpreadAttribute` information is missing, so anytime a spread attribute is found in JSX, `estraverse` throws an error. I think you need to add:

```js
XJSSpreadAttribute: ["arguments"]
```

**Comment by RReverser** [comment]
Thanks! estraverse-fb appeared before that functionality was added to JSX. Will add it.

**Comment by RReverser** [comment]
Added & published.
