### ISSUE TITLE
Upgrade peer dependency on estraverse

### ISSUE THREAD

**Issue by nzakas** [RReverser/estraverse-fb#4]
estraverse 2.0.0 was released, but I can't install it alongside estraverse-fb due to the peer dependency requirement.

Can you change the peer dependency version to be "latest"? Seems like since you're just patching Syntax and VisitorKeys, it should always continue to work so long as that interface doesn't change.

**Comment by RReverser** [comment]
Yep, should work.

**Comment by RReverser** [comment]
Fixed in 1.3.1.

**Comment by nzakas** [comment]
Thanks!
